apiVersion: v1
kind: ServiceAccount
metadata:
  name: model-deployer-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: model-deployer-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["serving.knative.dev"]
    resources: ["services"]
    verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: model-deployer-role-binding
subjects:
  - kind: ServiceAccount
    name: model-deployer-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: model-deployer-role
  apiGroup: rbac.authorization.k8s.io
